;;; build-nelisp-emacs-org-bridge-bundle.el --- generate normalized vendor Org bundle -*- lexical-binding: t; -*-

;;; Commentary:

;; Host-Emacs-side build step for the vendor-first Org lane.
;;
;; This mirrors the Magit bridge bundle shape, but the scope is narrower:
;; normalize the real vendored Org source closure needed for live loading into
;; an already-baked base NeLisp runtime image.  The generated bundle keeps
;; vendor source authoritative; it does not patch files under vendor/.

;;; Code:

(require 'standalone-source-normalize)

(defvar nelisp-emacs-org-bridge-bundle-output-file nil
  "Output path for the generated Org bridge bundle.")

(defvar nelisp-emacs-org-bridge-bundle-repo-root
  (expand-file-name ".." (file-name-directory
                          (or load-file-name buffer-file-name)))
  "Repository root used by the Org bridge bundle generator.")

(defvar nelisp-emacs-org-bridge-bundle-files
  '(("vendor/emacs-lisp/org/org-version.el" . org-version)
    ("vendor/emacs-lisp/org/org-element-ast.el" . org-element-ast)
    ("vendor/emacs-lisp/org/org-macs.el" . org-macs)
    ("vendor/emacs-lisp/org/org-compat.el" . org-compat)
    ("vendor/emacs-lisp/org/org-fold-core.el" . org-fold-core)
    ("vendor/emacs-lisp/org/org-fold.el" . org-fold)
    ("vendor/emacs-lisp/org/org-duration.el" . org-duration)
    ("vendor/emacs-lisp/org/org-faces.el" . org-faces)
    ("vendor/emacs-lisp/org/org-keys.el" . org-keys)
    ("vendor/emacs-lisp/org/org-cycle.el" . org-cycle)
    ("vendor/emacs-lisp/org/org-table.el" . org-table)
    ("vendor/emacs-lisp/org/org-pcomplete.el" . org-pcomplete)
    ("vendor/emacs-lisp/org/org-src.el" . org-src)
    ("vendor/emacs-lisp/org/org-macro.el" . org-macro)
    ("vendor/emacs-lisp/org/org.el" . org)
    ("vendor/emacs-lisp/org/ol.el" . ol)
    ("vendor/emacs-lisp/org/org-refile.el" . org-refile)
    ("vendor/emacs-lisp/org/org-clock.el" . org-clock)
    ("vendor/emacs-lisp/org/org-capture.el" . org-capture)
    ("vendor/emacs-lisp/org/org-datetree.el" . org-datetree)
    ("vendor/emacs-lisp/org/org-archive.el" . org-archive)
    ("vendor/emacs-lisp/org/org-agenda.el" . org-agenda)
    ("vendor/emacs-lisp/org/org-persist.el" . org-persist)
    ("vendor/emacs-lisp/org/org-element.el" . org-element)
    ("vendor/emacs-lisp/org/org-footnote.el" . org-footnote)
    ("vendor/emacs-lisp/org/org-list.el" . org-list)
    ("vendor/emacs-lisp/org/org-entities.el" . org-entities))
  "Ordered (RELATIVE-PATH . FEATURE) pairs loaded by the Org bridge bundle.")

(defvar nelisp-emacs-org-bridge-bundle-retained-defuns
  '(org-mode
    org-paste-subtree
    org-capture
    org-capture-select-template
    org-capture-finalize
    org-capture-set-target-location
    org-capture-fill-template
    org-macro--makeargs
    org-macro--set-templates
    org-macro--collect-macros
    org-macro--get-property
    org-macro--find-keyword-value
    org-macro--find-date
    org-macro--vc-modified-time
    org-macro--counter-initialize
    org-macro--counter-increment
    org-macro-initialize-templates
    org-agenda-mode
    org-agenda-list
    org-agenda-get-progress
    org-agenda-get-timestamps
    org-agenda-get-deadlines
    org-agenda-get-scheduled
    org-agenda-get-blocks)
  "Vendor Org defuns that must keep their real bodies in the bridge bundle.")

(defun nelisp-emacs-org-bridge-bundle--output-file ()
  "Return the resolved Org bridge bundle output path."
  (or nelisp-emacs-org-bridge-bundle-output-file
      (expand-file-name "build/nelisp-emacs-org-bridge-bundle.el"
                        nelisp-emacs-org-bridge-bundle-repo-root)))

(defun nelisp-emacs-org-bridge-bundle--self-provide-form-p (feature form-string)
  "Return non-nil when FORM-STRING is a top-level `(provide 'FEATURE)'."
  (let ((form (car (read-from-string form-string))))
    (equal form `(provide ',feature))))

(defun nelisp-emacs-org-bridge-bundle--write (output)
  "Normalize Org bridge sources and write OUTPUT."
  (make-directory (file-name-directory output) t)
  (with-temp-file output
    (insert ";;; nelisp-emacs-org-bridge-bundle.el --- generated vendor Org bundle -*- lexical-binding: t; -*-\n")
    (insert ";;; Generated by scripts/build-nelisp-emacs-org-bridge-bundle.el; do not edit.\n")
    (dolist (entry nelisp-emacs-org-bridge-bundle-files)
      (let* ((rel (car entry))
             (feature (cdr entry))
             (file (expand-file-name rel nelisp-emacs-org-bridge-bundle-repo-root))
             (saw-self-provide nil))
        (unless (file-readable-p file)
          (error "org bridge bundle: missing vendor source %s" file))
        (insert (format "\n;;; >>> %s (%s)\n" rel feature))
        (insert
         (format
          "(when (and (fboundp 'nelisp--write-stdout-bytes) (equal (getenv \"NEMACS_ORG_BUNDLE_TRACE_FILES\") \"1\")) (nelisp--write-stdout-bytes \"ORG-BUNDLE-FILE BEGIN %s\\n\"))\n"
          rel))
        (let ((standalone-source-normalize-enable-bundled-ignore-defuns nil)
              (standalone-source-normalize-force-retain-defun-symbols
               nelisp-emacs-org-bridge-bundle-retained-defuns))
          (dolist (form (standalone-source-normalize-file-to-form-strings file))
            (unless (nelisp-emacs-org-bridge-bundle--self-provide-form-p feature form)
              (insert (format "(unless (featurep '%s) %s)\n" feature form)))))
        (insert (format "(unless (featurep '%s) (provide '%s))\n" feature feature))
        (insert
         (format
          "(when (and (fboundp 'nelisp--write-stdout-bytes) (equal (getenv \"NEMACS_ORG_BUNDLE_TRACE_FILES\") \"1\")) (nelisp--write-stdout-bytes \"ORG-BUNDLE-FILE END %s\\n\"))\n"
          rel)))))
  output)

(defun nelisp-emacs-org-bridge-bundle-build-batch ()
  "Batch entry point for generating the Org bridge bundle."
  (let ((output (nelisp-emacs-org-bridge-bundle--output-file)))
    (nelisp-emacs-org-bridge-bundle--write output)
    (princ (format "nelisp-emacs-org-bridge-bundle: wrote %s\n" output))))

(provide 'build-nelisp-emacs-org-bridge-bundle)

;;; build-nelisp-emacs-org-bridge-bundle.el ends here
